name: flutterui_cli
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  archive: ^4.0.7
  args: ^2.7.0
  cli_util: ^0.4.2
  file: ^7.0.1
  http: ^1.4.0
  path: ^1.9.1
  pub_semver: ^2.2.0
  yaml: ^3.1.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
